- name: Fedora Setup
  hosts: localhost
  become: true

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Handle Config Files
      ansible.builtin.include_tasks: tasks/configs.yml
    - name: Add Repository
      ansible.builtin.include_tasks: tasks/repos.yml
