- name: Create Configs Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "700"
  loop: "{{ configs_dir }}"

- name: Place Configs Files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "700"
  loop: "{{ configs_dest }}"