- name: Install Dnf Packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ repo_packages }}"

- name: Install Flatpacks
  ansible.builtin.shell: "flatpak install {{ item }} -y"
  loop: "{{ flatpacks }}"

- name: Install Other Packages
  ansible.builtin.shell: "{{ item }}"
  args:
    executable: /usr/bin/fish
  loop: "{{ other_packages }}"