- name: Install Dnf Packages
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: present
  loop: "{{ repo_packages }}"

- name: Install Other Packages
  ansible.builtin.command: "{{ command }}"
  loop: "{{ other_packages }}"