- name: Install Dnf Packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ repo_packages }}"

- name: Install Other Packages
  ansible.builtin.shell: "{{ item }}"
  args: 
    executable: /usr/bin/fish
  loop: "{{ other_packages }}"