- name: Install Dnf Packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ repo_packages }}"

# - name: Install Other Packages
#   ansible.builtin.command: "{{ item }}"
#   loop: "{{ other_packages }}"