- block:

  - name: Install Distribution GPG Keys
    dnf:
      name: distribution-gpg-keys
      state: present

  - name: Add RPM Fusion NonFree key
    rpm_key:
      key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_version }}"
      state: present

  - name: Add RPM Fusion NonFree
    dnf:
      name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
      state: present


- block:
  
  - name: Add VScode Repo key
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  
  - name: Add VScode Repo
    yum_repository:
      name: code
      description: Visual Studio Code
      file: vscode
      baseurl: "https://packages.microsoft.com/yumrepos/vscode"
      gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
      gpgcheck: yes